version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=member-service
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306