version: "3.3"
services:
  jenkins-alpine:
    image: jenkins/jenkins:2.131-alpine
    ports:
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker